### PR TITLE
Fixed automated Gitpod dev setup

### PR DESCRIPTION
**Pull request by jankeromnes**
Hey @techwithtim! 👋 Thanks a lot for making really cool video tutorials!

I noticed that your Gitpod setup was almost perfect -- `.gitpod.yml` was just missing an explicit reference to the dockerfile (contrary to `.gitpod.yml`, we don't currently detect `.gitpod.dockerfile` automatically -- I agree that's confusing and maybe we should!)

I also took the liberty to tweak the setup a bit more:
- `.gitpod.yml` now directly references our `gitpod/workspace-full-vnc` image (so you won't have to fork & maintain your dockerfile)
- I've configured port `6080` (the remote desktop) to automatically open a preview when active
- `GUI.py` will be both opened in the Editor and started in the Terminal on start-up
- I've added a Gitpod button to your README (please let me know if you don't like it)

Here is what it looks like:

[Open in Gitpod](https://gitpod.io/#https://github.com/jankeromnes/Sudoku-GUI-Solver/blob/master/GUI.py)
Screenshot 2019-06-25 at 09 47 53
Hope this helps! 🙂 Please let me know if there is anything I can improve in this setup.

### CODE REVIEW

**Comment by techwithtim** [comment]
Absolutely awesome!!

Thanks so much Jan for the quick fix, not I can get ready to film the video I had planned :)

Thanks,
Tim

**Comment by techwithtim** [comment]
@jankeromnes sorry if this is not the correct place, I couldn't find your email. I've been trying to use the sudo command to install some packages in gitpod and was having some issues. Was wondering if you could point me in the right direction. 

sudo error

**Comment by jankeromnes** [comment]
@techwithtim No worries! My email should be in your `git log` now, but here works fine too. 😄

Yes, unfortunately `sudo` is disabled when you start a workspace, for security reasons. Judging from your other issue comment, I guess you've found the solution already, but here it is anyway just in case:

To use `sudo`, e.g. to `apt-get install` things in Gitpod, you need to make a `.gitpod.dockerfile` again.

Simply replace:

```yaml
image: gitpod/workspace-full-vnc
```

in your `.gitpod.yml` by:

```yaml
image:
  file: .gitpod.dockerfile
```

And then add this new file and call it `.gitpod.dockerfile`:

```Dockerfile
FROM gitpod/workspace-full-vnc

USER gitpod
RUN sudo apt-get update \
 && sudo apt-get install -y \
  python-tk \
 && sudo rm -rf /var/lib/apt/lists/*
```

And that's it. 🙂 Please let me know if you have any other questions (here, or via Spectrum, or by email, as you prefer).

**Comment by techwithtim** [comment]
Thanks Jan, 

I did get it figure out, only problem now is I can’t delete any failed workspaces! Which means I actually can’t run any more as I can only run 8 at once.

Thanks,
Tim

**Comment by jankeromnes** [comment]
@techwithtim cool that you got it to work!

But that other issue sounds bad. The limit of 8 workspaces is for _running_ them all in parallel (in practice you almost never do that -- unless you're a much better multi-tasker than I am 😅)

I also have many failed workspaces from past dockerfile experiments, but I've never had to delete those, as they're not longer "running" so don't count toward the limit.

Do you actually get the "only 8 workspaces allowed in parallel" error page even when fewer than 8 workspaces are shown as "running" in your dashboard?

That would be a huge problem that we'd need to fix in Gitpod itself.

**Comment by jankeromnes** [comment]
(and also we should allow deleting failed workspaces, as they might be distracting in your workspace list, but until now I considered this more like a cosmetic/convenience issue)

**Comment by techwithtim** [comment]
The issue I was having was I kept updating my dockerfile and running new workspaces that kept crashing. This is because I messed up my Linux commands (in the docker file) so many times in such quick succession. So what ended up happening (at least my guess ) is that these failed builds were still “running” and could not be stopped. So when I eventually got to 8 failed builds they were all running and I couldn’t start anymore workspaces. The reason I wanted to delete them was because the STOP button wouldn’t show up beside where the START button was in the dashboard. So my theory was the only way to stop them would be to delete them. Anyways it seems it takes about 1.5 hours before they stop running. So your real issue is when idiots like me make 8 builds fail within an hour and a half. 

Make sense?

@jankeromnes

**Comment by jankeromnes** [comment]
Thanks a lot @techwithtim for the very helpful explanation! It does make sense, and this should absolutely be fixed in Gitpod. I'll try to see to it, and I'll keep you posted. 🙂

**Pull request merged**
